=== KarinaMakarevich/epamCources/Parser/src/main/webapp/data/postcard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://by.epam.makarevich/postcard"
           xmlns:tns="http://by.epam.makarevich/postcard"
           elementFormDefault="qualified">

    <xs:complexType name="Postcard">
        <xs:sequence>
            <xs:element name="postcard-id">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="[A-Z]{2}\d{12}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="theme" type="xs:string"/>
            <xs:element name="postcard-type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="congratulatory"/>
                        <xs:enumeration value="usual"/>
                        <xs:enumeration value="advertising"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z]+([A-Z]?[a-z]?)+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="year">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minExclusive value="1900"/>
                        <xs:maxInclusive value="2017"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="author-information">
                <xs:complexType>
                    <xs:attribute name="is-known" type="xs:boolean" use="required"/>
                    <xs:attribute name="author" type="xs:string" default="Unknown-Author"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="value">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="historical"/>
                        <xs:enumeration value="collectible"/>
                        <xs:enumeration value="thematic"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="was-send" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BirthdayPostcard">
        <xs:complexContent>
            <xs:extension base="tns:Postcard">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="year-count">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minExclusive value="1"/>
                                <xs:maxInclusive value="200"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="content">
                        <xs:complexType>
                            <xs:attribute name="text" type="xs:string" use="required"/>
                            <xs:attribute name="is-in-verse" type="xs:boolean" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ComplimentaryPostcard">
        <xs:complexContent>
            <xs:extension base="tns:Postcard">
                <xs:sequence>
                    <xs:element name="place" type="xs:string"/>
                    <xs:element name="men-count" type="xs:positiveInteger"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="postcard" type="tns:Postcard" abstract="true"/>
    <xs:element name="birthday-postcard" type="tns:BirthdayPostcard" substitutionGroup="tns:postcard"/>
    <xs:element name="complimentary-postcard" type="tns:ComplimentaryPostcard" substitutionGroup="tns:postcard"/>

    <xs:element name="old-cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:postcard"
                            minOccurs="2"
                            maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KarinaMakarevich/epamCources/Parser/src/main/webapp/data/postcard.xml
<?xml version="1.0" encoding="UTF-8"?>
<old-cards xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://by.epam.makarevich/postcard"
           xs:schemaLocation="http://by.epam.makarevich/postcard  postcard.xsd"
>
    <birthday-postcard>
        <postcard-id>FF123456782000</postcard-id>
        <theme>jjj</theme>
        <postcard-type>advertising</postcard-type>
        <country>USA</country>
        <year>1999</year>
        <author-information is-known="true"/>
        <value>collectible</value>
        <was-send>true</was-send>
        <name>jjjjkjkjkjkkj</name>
        <year-count>150</year-count>
        <content text="hhhhjj" is-in-verse="true"/>
    </birthday-postcard>
    <complimentary-postcard>
        <postcard-id>KK123654789222</postcard-id>
        <theme>nam</theme>
        <postcard-type>usual</postcard-type>
        <country>Belarus</country>
        <year>2014</year>
        <author-information is-known="true"/>
        <value>historical</value>
        <was-send>false</was-send>
        <place>Minsk</place>
        <men-count>20</men-count>
    </complimentary-postcard>
    <complimentary-postcard>
        <postcard-id>AB123456789124</postcard-id>
        <theme>Beu</theme>
        <postcard-type>advertising</postcard-type>
        <country>Russia</country>
        <year>2010</year>
        <author-information is-known="false"/>
        <value>thematic</value>
        <was-send>false</was-send>
        <place>Nesvizh</place>
        <men-count>12</men-count>
    </complimentary-postcard>
</old-cards>
